### ISSUE TITLE
Get a 0.1.0a0 release on pypi

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#104]
Talking with @salotz about this I don't think it could hurt to get a `0.0.0.dev0` version up on pypi just so we've got the name and what not.

I guess I could make a little milestone to fix a couple bugs before this?
It's probably fine to just start pushing up dev releases here and there for peeps who prefer that.
No warranty or support of any sort will come with them of course.

**Comment by salotz** [comment]
Ya after you showed PEP 440 I'm really getting into the dev release things. Before I was making patch releases just because I screwed up the packaging stuff. Currently working on testing it with a personal package for gotchas etc. I will try to transfer these BPs when I do #100.

Discuss: Maybe it should be a `0.0.0a0.dev` release?

**Comment by ryanhiebert** [comment]
Prereleases are a pain to work with under pipenv. That's a pipenv issue, but it does mean that I often have to avoid them for my work. Which is fine right now, but when I feel that there's enough in place for me to be writing real code against, I'm going to be coming asking for a proper release, just so I don't have to fight my tooling.

I think a good warning in the readme that this is still early stages is perfectly reasonable. I tend to think that just going to 1.0 is good, and just be really clear and upfront that big changes are expected, and there won't be advance warning about them, only that you'll bump the major version when it breaks stuff.

**Comment by ryanhiebert** [comment]
But yeah, getting something on PyPI is a very good idea.

**Comment by salotz** [comment]
> Prereleases are a pain to work with under pipenv. That's a pipenv issue

Interesting. I haven't used `pipenv` but there was some FUD going around that convinced me to not really use it. Apparently `pip-tools` does the same things and is a little simpler. Not sure if it has similar problems with pre-releases /et. al/ though. I'll make that part of my investigation.

What is the issue with those and pipenv?

**Comment by goodboy** [comment]
@ryanhiebert I've run into said issues with `pipenv` (which actually I'm not sure I want to use anymore in `piker`) when using `anyio` and `trio-typing`. I'm not sure we should hold off on using `.dev` because of `pipenv` though especially since you can still just pull from the git repo and tie to a commit if necessary.

I fee like sticking to peps over `pipenv`'s limitations is probably a little more sane :wink:

**Comment by goodboy** [comment]
Also, @salotz, I'm partial to using `.` seperator for the written (non-normal) form we codify in the repo if that's ok by you. So we go with `0.0.0.alpha0.dev0` as is allowed in the [pre-release separators section](https://www.python.org/dev/peps/pep-0440/#pre-release-separators). I'm not huge on peeps having to reverse-lookup normal form to get english; much rather the other way around :smile_cat:

**Comment by salotz** [comment]
@goodboy On one hand explicit is better than implicit. Although I think I value the consistency between what will be shown on PyPI and what would be on the git tag more personally.

Perhaps this is bikeshedding so don't pay too much mind, just my thoughts on the matter.

**Comment by dxflores** [comment]
I would defer publishing to PyPi until later. I just don't think that it is worth the hassle right now, nor do I think that the project should fall into the "no warranty - no support atm". In all honesty, if anyone wants to try the project on the current alpha state, they can very easily clone the repo or just install directly from git. A few other thoughts: I think we should define a 'minimum viable version' (e.g. the current one with perhaps a few mods) and keep that in the main branch for people to download and try, however I think that we should work on a dev branch so we aren't afraid to break things up and/or explore major changes to the API or the overall structure of the program.

**Comment by ryanhiebert** [comment]
I'm fine with leaving it in the repo, although a PyPI release when we have a minimal viable product sounds good to me.

AFA working in a dev branch, I'm mostly against that. I've found that overhead to be very annoying, and splitting attention. I'm all for feature branches. Long lived ones if needed. But I don't tend to think that having multiple "head" branches is worthwhile, unless you are cutting off supported versions that will have their own minor releases (like Django).

**Comment by goodboy** [comment]
> AFA working in a dev branch, I'm mostly against that. I've found that overhead to be very annoying, and splitting attention.

Agreed. Sorry @dxflores gotta vote against that. I would rather keep `master` nimble and moving. We can always tag and bag releases as we go. If we end up having a real need for a stable branch we can look at it when someone requests it.

**Comment by goodboy** [comment]
>Although I think I value the consistency between what will be shown on PyPI and what would be on the git tag more personally.

Hmm good point. It's too bad the normalization happens at all :laughing:

**Comment by salotz** [comment]
@goodboy I agree its very anti-zen thing. I think its so they can support dependency solving though which is a cursed problem. Although I didn't catch whether normalization happens at "solve time"
or at "package publication" time.  :thinking: 

Like if we publish with `0.0.0.alpha0.dev0` will it show up on PyPI as `0.0.0a.dev0` (or whatever normalized form)?

Or if when someone puts in their specs: `tractor==v0.0.0-a.dev` it will do the right thing?

In any case the least amount of indirection is by just doing everything in normal form even if it is "implicit" rather than explicit. And it's not a huge overhead parsing 'a' -> 'alpha' for most people, especially the devs who are the only ones that should see it.

**Comment by goodboy** [comment]
@salotz yeah i do like not having mismatched forms. Hmm ok. So can we agree on `0.0.0.a0.dev0`? Or do you want it in *true normal form*? In that case what do we use to generate that output?

**Comment by goodboy** [comment]
Yo @salotz I think I'm gonna just go ahead with my last comment. I'm pretty sure it will work itself out and if not we can always fix it later.

**Comment by goodboy** [comment]
Thanks to  bluecolor/tractor#1 this is still a possibility 😂 

Going to push up a `.dev0` release stat!

**Comment by altendky** [comment]
Just a quick FYI that the `packaging` package has [`packaging.utils.canonicalize_name()`](https://packaging.pypa.io/en/latest/utils.html#packaging.utils.canonicalize_name) to apply the PEP 440 normalization, if you want to go that route.  Here's an example admin tool calling it.

https://github.com/twisted/towncrier/blob/7f209109513534d4c3e9defc732fa43ce0ff99aa/admin/canonicalize_version.py
```python
import click
import packaging.utils


@click.command()
@click.argument("version")
def cli(version):
    """Canonicalizes the passed version according to PEP 517."""
    canonicalized_version = packaging.utils.canonicalize_version(version)

    click.echo(canonicalized_version)


if __name__ == "__main__":
    cli()
```

**Comment by goodboy** [comment]
Not sure what to think:

```python
[nav] In [8]: canonicalize_name('0.0.0.0alpha0.dev0')
Out[8]: '0-0-0-0alpha0-dev0'

[ins] In [9]: canonicalize_name('0.0.0.0a0.dev0')
Out[9]: '0-0-0-0a0-dev0'
```

**Comment by altendky** [comment]
`s/name/version/`

**Comment by goodboy** [comment]
Hmm not sure I follow?

**Comment by graingert** [comment]
@goodboy the function is canonicalize_version not canonicalize_name

**Comment by goodboy** [comment]
😂 thxxx

**Comment by goodboy** [comment]
```python
[nav] In [3]: canonicalize_version('0.0.0.0alpha0.dev0')
Out[3]: '0a0.dev0'
```

Look ma, i can read **and** write 🏄🏼

**Comment by goodboy** [comment]
Ok so I'm thinking first pipy release can use:

```
[nav] In [14]: canonicalize_version('0.0.0alpha0.dev0')
Out[14]: '0a0.dev0'
```

we'll stick the input: `'0.0.0alpha0.dev0'` into the `__init__.py` module
and read it into `setup.py`?

Or is everyone in favor of always using the canonical form?

**Comment by graingert** [comment]
setuptools can parse the version from your `__init__.py` if you use `setup.cfg`

```
version= :attr tractor.__version__
```

**Comment by graingert** [comment]
Twisted again for the example https://github.com/twisted/twisted/blob/trunk/setup.cfg#L3

**Comment by goodboy** [comment]
Ok trying to keep this as simple as possible to just get something up (since I've got caught up in a lot of people's opinions on release policies and options).

As per https://semver.org/#faq

> How should I deal with revisions in the 0.y.z initial development phase?

>The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

So I think we'll just make it a first alpha release to get something on pypi and then we'll figure out a `.devX` and/or git based tagging for incremental development releases through discussion in #116.

I also want to likely automate the changelog stuff with `towncrier` going forward among other things.

I'm going to merge this branch, do a tag and a push to pypi if noone else has any quiffs with the current state.

**Comment by goodboy** [comment]
https://pypi.org/project/tractor/0.1.0a0/
