### ISSUE TITLE
Add a simple real-time streaming example to the README

### ISSUE THREAD

**Issue by ghost** [goodboy/tractor#114]
This is more an opinion, and there's clearly no right or wrong, however when I come across a project on GitHub I don't like it if there's not at least a basic example of how to use/what the package looks like on the README file. The suggestion is that we either copy/paste the first example (the movie scene) from the docs, or just make a new one.

2nd: I think the 'readthedocs' link should be among the others in the main text, instead of on the project description.  

Happy to work this out. Let me know.

**Comment by goodboy** [comment]
@dxflores I do think in example in the readme is good. [`trio` doesn't do it](https://github.com/python-trio/trio) but we're also not as established ;)

I wonder if maybe a more all-encompassing yet simple example could be drafted up?
I would rather have something which demonstrates streaming (and maybe cancellation).

Anyone got any ideas of a simple streaming task that might also be just generally useful?

**Comment by goodboy** [comment]
@dxflores oh and there technically *is* a link to the docs in the readme via the badge but I guess you want a more explicit link / header section?

**Comment by dxflores** [comment]
Agree with the streaming example. Also it should be non abstract and easier to understand.

Yes, I think the link should be more explicit. E.g. here are our docs, here are trio's etc..

**Comment by goodboy** [comment]
@dxflores feel free to PR both in if you want :)

**Comment by dxflores** [comment]
Cool. Will do.

**Comment by goodboy** [comment]
Hmm, I'm thinking I'm going to put an example from a trading indicator I use.
An example of a streaming trend detector on financial series seems to fit this.
We can maybe follow it up with some basic ML stuff that I've got going related to it on tick data.

**Comment by goodboy** [comment]
Got an idea for this now using some new soft-realtime shared memory stuff from `piker` which we'll likely breakout into a new `tractor` dependent.

I'd like to demonstrate the [streaming maximum-minimum filter](https://arxiv.org/abs/cs/0610046) algorithm which will (eventually) be used internally in `piker` anyway.

A reference sync [python implemenation](https://github.com/lemire/pythonmaxmin) can be the start point.

**Comment by goodboy** [comment]
Closing in favor of the much larger #157 which should include tasks for content that will include this.

Also OP has literally vanished 😂
