### ISSUE TITLE
trip doesn't do control-C right...

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#115]
Thought I messed something up with the `trio_run_in_process` port but testing with some `piker` apps I realized that everything works fine with `ctl-c` when using `start_method='forkserver'`. 

See ethereum/trio-run-in-process#4 for the deats!

**Comment by goodboy** [comment]
Heh, also seems like it's being somewhat unmaintained as I've yet to receive any feedback on this issue..

**Comment by ryanhiebert** [comment]
Bummer.

**Comment by goodboy** [comment]
@ryanhiebert indeed. I'm even fine to fix it myself but I'd rather do that in a fork and start working forwards if no-one is going to provide feedback..
