### ISSUE TITLE
Let's roll our own subproc spawner ("the way the experts would")

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#117]
After all the headaches from trying to integrate `trio-run-in-process`:
- #115, #96 as local standouts for which I created ethereum/trio-run-in-process#4
- the mess of 3 repos that aren't doing anything novel and overlap each other as per discussion in ethereum/trio-run-in-process#6
- the over complexity of the design and spawning logic (as discussed by me [here](https://github.com/ethereum/trio-run-in-process/issues/6#issuecomment-634447691) and confirmed by nathaniel [here](https://github.com/python-trio/trio/issues/5#issuecomment-529272338))
- the divergence of [goals of the author](https://github.com/ethereum/trio-run-in-process/issues/6#issuecomment-634727926) from [our own](https://tractor.readthedocs.io/en/latest/?badge=latest#philosophy)

I think it's time to move on to more general pastures :wink: 

There was some good refactoring and re-design that came out of this in #95 including the discovery that stdstreams if semaphored correctly can allow for `pdb++` to somewhat work out of the box (towards #113).

I would like to discuss with `anyio` and `trio` core devs about design and goals to eventually factor this functionality into the core async lib as necessary.

**Comment by ryanhiebert** [comment]
Thanks for this. Yeah, I think the approach you're mentioning makes sense. And, when it's done right, I think it absolutely makes sense for it to be in the core libraries.

**Comment by goodboy** [comment]
Relevant links to get this rolling:
- [`anyio` subproc support + todo](https://github.com/agronholm/anyio/issues/9)
- discussion about [worker pools in `trio`](https://github.com/python-trio/trio/issues/5)
- discussion about [spawning processes from nurseries](https://github.com/python-trio/trio/issues/1104)
- the tagged [subprocess issue list from `trio`](https://github.com/python-trio/trio/issues?q=is%3Aissue+is%3Aopen+label%3Asubprocesses+)
