### ISSUE TITLE
Log the trio task name

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#13]
You can get it with `trio.current_actor().name` and likely have to make some kind of custom [formatter with `logging`](https://docs.python.org/3/library/logging.html#logging.Formatter).

**Comment by tgoodlet** [comment]
Hmm looks like [`LoggingAdapter`](https://docs.python.org/3/howto/logging-cookbook.html#adding-contextual-information-to-your-logging-output) is the recommended way to accomplish this.
