### ISSUE TITLE
Add logo and github actions badge to readme

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#153]
[Atomix does it](https://github.com/atomix/atomix#readme) using their own website but I think we can using web service [provided by github](https://stackoverflow.com/a/14494775)?

So should be something like:
 `"![alt text](https://github.com/[goodboy]/[tractor]/blob/[master]/logo.svg?raw=true)"`

The actions badge type and url can be figure out [here](https://actions-badge.atrox.dev/).

**Comment by goodboy** [comment]
This might be the more adult way to do it with an *assets branch*?
https://stackoverflow.com/a/42677655

**Comment by goodboy** [comment]
Actually, [`alakitty`](https://blog.christianduerr.com/), [does it even better using html](https://raw.githubusercontent.com/alacritty/alacritty/master/README.md).

**Comment by goodboy** [comment]
Go this working with a plain old `.. image:` `ReST` directive in #163 and just putting our readme inside the docs dir (which I didn't realize you could do).

Also found this [blog post](https://olivermak.es/2016/01/svg-in-github-readme/) on sticking `.svg` files into GH readmes though didn't end up using it since it was markdown/html based which didn't seem to work when done in the `.rst` format.

So the logo part is closed by 61611ee and the actions badge part in bba47e4c7a2a.

**Comment by ryanhiebert** [comment]
OK, that's cool. I didn't know the readme could be in the docs folder.
