### ISSUE TITLE
Switching to pdbpp is making it impossible to install with pypy and git

### ISSUE THREAD

**Issue by grizzlybearg** [goodboy/tractor#364]
I get the followinf error when trying to install using pypy:
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
tractor depends on pdbpp@ git+https://github.com/pdbpp/pdbpp@76c4be5#egg=pdbpp ; python_version > "3.9"

I can't install using git because I get this error:
`PS C:\Users\user> pip install git+git://github.com/goodboy/tractor.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+git://github.com/goodboy/tractor.git
  Cloning git://github.com/goodboy/tractor.git to c:\users\user\appdata\local\temp\pip-req-build-ryqbr1ew
  Running command git clone --filter=blob:none --quiet git://github.com/goodboy/tractor.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-ryqbr1ew'
  fatal: unable to connect to github.com:
  github.com[0: 20.87.225.212]: errno=Unknown error

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/goodboy/tractor.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-ryqbr1ew' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/goodboy/tractor.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-ryqbr1ew' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by Zaczero** [comment]
Such a good project, yet, I cannot install it.

**Comment by goodboy** [comment]
@Zaczero 😂 

Yeah sorry our last alpha was borked on pypi... SORRY

been meaning to do another release but it's just been lower on the TODO list.

Install from git should work no?

> fatal: unable to connect to github.com:
github.com[0: 20.87.225.212]: errno=Unknown error

Seems to be some non-tractor issue that @grizzlybearg experienced 🤔 

ALSO, and btw we already know about this issue 😂 
https://github.com/goodboy/tractor/issues/323

@Zaczero @grizzlybearg RE the `pdbpp` thing, we aren't supporting it any more either so please migrate to `pdbp` as per https://github.com/goodboy/tractor/pull/358

If there's anything else I can help with please LMK.

I will try to get a new pypi release out this week.

---
ALSO, how does everyone feel about using `poetry` going forward?

**Comment by goodboy** [comment]
@grizzlybearg Hmm. 

It's the same error as from OP yah?

Technically we haven't really tested nor claimed to support `pypy` if you're talking about the interpretter / JIT. I'm guessing you just mispelled PyPi? Maybe clarify that part 😉 

In terms of installing with `pip` from github, maybe try cloning the rep and installing in [editable mode](https://setuptools.pypa.io/en/latest/userguide/development_mode.html)?


---
> ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
tractor depends on pdbpp@ git+https://github.com/pdbpp/pdbpp@76c4be5#egg=pdbpp ; python_version > "3.9"

- We don't support python <= 3.10 on master any more.
- I'm pretty sure there's no way if you did this from master that any dep on `pdbpp` exists (it should be `pdbp` now), so i'm not sure how you're getting this error unless you're on old code.

AGAIN, PyPi install are known to borked rn, i already linked the existing issue.

**Comment by goodboy** [comment]
On a related note, after having used `poetry` in a couple projects now I'm fairly convinced it's a much more sane way to go and so likely as part of addressing whatever underlying issue is causing this we'll use that re-packaging task to solve it 😎

**Comment by Zaczero** [comment]
This is a fresh ubuntu image with git, python, pip installed.
None of the installation instructions from the [README](https://github.com/goodboy/tractor#install) work.

![image](https://github.com/goodboy/tractor/assets/10835147/f66e4cd3-e449-401e-bbed-907dfc438640)

![image](https://github.com/goodboy/tractor/assets/10835147/3b2e1f62-715d-4e08-9bff-a7c0f2a747b6)

**Comment by goodboy** [comment]
@Zaczero your 2nd command is timing out on the network?

I'm not sure i can help much with that.
Either way try doing a from source install by cloning and cd-ing to the repor dir and running `pip install -e ./`

Will hopefully get to patching this all up and another release in the next month once a ton of patches get landed.

**Comment by Zaczero** [comment]
![image](https://github.com/goodboy/tractor/assets/10835147/c608d55e-00aa-40e7-ad7f-de1ee309e176)

I'm not sure what more to express here. The problem seems isolated to the Tractor package in my case. It's possible that it's experiencing timeouts due to its continued use of the deprecated <kbd>git://</kbd> protocol. As discussed in this GitHub blog post (https://github.blog/2021-09-01-improving-git-protocol-security-github/). I'm aware that numerous installation approaches exist. However, I'd kindly request that the functional methods be documented in the Installation section of the README.

**Comment by goodboy** [comment]
Ok well our CI thinks that installs work just fine, otherwise this job would fail 😉. Mind you this is doing manual sdist installs with ` python -m pip install dist/*.zip`..

https://github.com/goodboy/tractor/actions/runs/6001334998/job/16275291910

> However, I'd kindly request that the functional methods be documented in the Installation section of the README.

Yes indeedy 😂 we for sure do not want to have the legacy url syntax in there.
I'm going to be pushing up some dev work today and will try to get the readme up to snuff for you to test

**Comment by goodboy** [comment]
> As discussed in this GitHub blog post (https://github.blog/2021-09-01-improving-git-protocol-security-github/).

FWIW, we'll of course quickly accept a patch for this to the README 😉 `

**Comment by goodboy** [comment]
Ok so we need to switch to the https url form for the readme:

https://stackoverflow.com/a/20101940
