### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by chrizzFTD** [goodboy/tractor#59]
Hi, this looks like a great project!

I wanted to give it a try but after installing via `pip install git+git://github.com/tgoodlet/tractor.git`, importing tractor fails because [forkserver](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) seems to not be available on my os (windows10):
```python
Python 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tractor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\tractor19030502\lib\site-packages\tractor\__init__.py", line 18, in <module>
    from ._trionics import open_nursery
  File "C:\ProgramData\Miniconda3\envs\tractor19030502\lib\site-packages\tractor\_trionics.py", line 21, in <module>
    ctx = mp.get_context("forkserver")
  File "C:\ProgramData\Miniconda3\envs\tractor19030502\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\ProgramData\Miniconda3\envs\tractor19030502\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'forkserver'
>>>
```
Any plan on adding windows support in the future?

**Comment by tgoodlet** [comment]
Hey @chrizzFTD thanks for attempting to give it a try :smile: 

Yes, unfortunately no Windows support yet :cry: 
I don't really use windows at all but I definitely do want to add support!

It should be possible to use the [spawn method from `multiprocessing`](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).
I've been meaning to try this out since it should work on linux as well.

You're very welcome to try and [add it yourself](https://github.com/tgoodlet/tractor/blob/master/tractor/_trionics.py#L21) though I have no idea it will work out of the box.
If you're not interested I could definitely use your help testing!

I've made #60 for that specific task and then hopefully adding it solves this :+1:

**Comment by tgoodlet** [comment]
@chrizzFTD mind trying out #61's branch to see if it works for you on windows?

**Comment by chrizzFTD** [comment]
Yes, thank you so much for taking a look so quickly @tgoodlet  😃 

I've left some updates on https://github.com/tgoodlet/tractor/pull/61#issuecomment-470053512, but in short, the only issue I'm seeing is (because of the same [windows deal](https://github.com/python-trio/trio/blob/d1efdd5f0f1f3e1b4eab872e87ff214d392dcc61/trio/hazmat.py#L26-L34)):

```
trio.MultiError: AttributeError("module 'trio.hazmat' has no attribute 'wait_readable'"), AttributeError("module 'trio.hazmat' has no attribute 'wait_readable'")
```

I'm keen on helping testing as much as possible!

**Comment by tgoodlet** [comment]
>I'm keen on helping testing as much as possible!

@chrizzFTD awesome!

>because of the same windows deal

Indeed. I'll coordinate with you on #61.

**Comment by tgoodlet** [comment]
Hmm I wonder if part of solving this should be adding a CI job too.
Looks like [travis started supporting it late last year](https://blog.travis-ci.com/2018-10-11-windows-early-release)!

**Comment by tgoodlet** [comment]
@njsmith tipped me to [free vms from microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) for testing purposes as well.

**Comment by goodboy** [comment]
Just an update, as of #61 and #62 we do have working windows support both verified in manual testing by @chrizzFTD and now [in travisCI](https://github.com/goodboy/tractor/blob/master/.travis.yml#L5).

There's still some kinks to work out ([unreliable CI builds](https://travis-ci.org/goodboy/tractor/jobs/597972125) it seems) as well as [some more documentation needed](https://github.com/goodboy/tractor/pull/61#issuecomment-541600098) to get windows users working well with `multiprocessing` gotchas.

**Comment by goodboy** [comment]
The unreliable CI builds seem to be either a race condition in determining the "arbiter" actor or some weird issue with being [unable to find the `pip` module](https://travis-ci.org/goodboy/tractor/jobs/597972125)?

I want to get #79 docs complete before considering this done as well.

**Comment by goodboy** [comment]
Also need to update the [listed OS support](https://github.com/goodboy/tractor/blob/master/setup.py#L35) in `setup.py`.
