### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#62]
As per #59 being resolved we should start running the test suite on windows.

Since [travis doesn't have python support yet on windows](https://blog.travis-ci.com/2018-10-11-windows-early-release) we could try out what `trio` does with the [azure pipelines](https://github.com/python-trio/trio/blob/master/azure-pipelines.yml) which are now [free for open source projects](https://samcogan.com/free-azure-build-pipelines-for-open-source-projects/).

**Comment by tgoodlet** [comment]
Oh and there's also [free vms from microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) for manual testing purposes if needed.

**Comment by goodboy** [comment]
Huh, looks like if you don't need a compiler it [actually is possible to do this on travis](https://travis-ci.community/t/python-support-on-windows/241/5)?

**Comment by goodboy** [comment]
@chrizzFTD just pinging you to let you know I am still going to work on this. 
I changed my username (finally got ahold of the one I want) in case that was confusing :smile:

**Comment by chrizzFTD** [comment]
Hey @goodboy, nice username & thanks for the update!

I’ve been away for the last few weeks but looking forward playing more with tractor in the next days and helping with anything possible 😃

**Comment by goodboy** [comment]
@chrizzFTD pinged you in #74!
