### ISSUE TITLE
Do we need to support invoking sync functions?

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#77]
@jtrakk made a good point [in gitter](https://gitter.im/python-trio/general?at=5cd0f94e3b6cb0686ab737d4) that supporting both async and regular functions for remote invocation is a bit odd and probably unnecessary. I think I agree; there ain't nothing a regular func can do that an async one can't. Unless I'm forgetting something I think it should be fine to just remove support for regular functions?

Off hand it would allow removing the slew of checks in [`_actor._invoke()`](https://github.com/goodboy/tractor/blob/master/tractor/_actor.py#L62).

**Comment by ryanhiebert** [comment]
I'd be in favor of only supporting async functions, for exactly the reasons you describe. I don't think there's anything significant to be gained, but there is additional complexity that could easily be avoided.

**Comment by goodboy** [comment]
See the comment in richardsheridan/trio-parallel#2 which I think is more fuel for this change.

**Comment by goodboy** [comment]
Yah, I'm thinking for a `.alpha0` release we just drop remote sync function calling support and defer to @richardsheridan's project.

**Comment by goodboy** [comment]
Yeah so TLDR: is that if we're calling sync funcs in some remote actor you'll need the `tractor` runtime **anyway** which means you should have the ability to wrap the call in an async func - so there should be no benefit to supporting that wrapping inside [`_actor._invoke`](https://github.com/goodboy/tractor/blob/master/tractor/_actor.py#L73).

I also think we should make a alt-projects list in the readme and point to others for this kind of thing.

**Comment by goodboy** [comment]
We already have a pointer to `trio-parallel` in the readme, so just need a PR removing the support now.
